export enum EventTopicTypeEnum{
  INTRO = 'INTRO',
  DETAILS = 'DETAILS',
  TRANSPORTATION = 'TRANSPORTATION',
  VENUE = 'VENUE',
  ACCOMMODATION = 'ACCOMMODATION',
  LOCAL_TRANSPORT = 'LOCAL_TRANSPORT',
  FOOD = 'FOOD',
  OTHER = 'OTHER',
  BVCM = 'BVCM',
}
