export enum FormControlTypeEnum {
  TEXT = 'TEXT',
  NUMBER = 'NUMBER',
  TEXTAREA = 'TEXTAREA',
  CHECKBOX = 'CHECKBOX',
  SINGLE_CHOICE_CHECKBOX = 'SINGLE_CHOICE_CHECKBOX',
  RADIO = 'RADIO',
  DATE = 'DATE',
  DATE_RANGE = 'DATE_RANGE',
  PERCENTAGE = 'PERCENTAGE',
  SELECT = 'SELECT',
}
